### ISSUE TITLE
Update the content of the About Page on Weavly website

### ISSUE THREAD

**Issue by sepidehshahi** [codelearncreate/weavly.org#852]
Please update the following sections on the about page: https://weavly.org/about/

- [ ] Change the text in the "Who we are section" to this: 
Weavly is a collaborative effort between the Inclusive Design Research Centre, IRIS Institute, and the Bridges Canada. This project is funded by the Innovation, Science and Economic Development Canada’s Accessible Technology Program.

- [ ] Add one more tile for the IRIS institute and include:

- Blurb: [TBD]
- Image: [TBD]
- link to their website: https://irisinstitute.ca/

- [ ] Change the text in the "Connect" section to this: 
Please email the project leads at the Inclusive Design Research Centre and the IRIS institute if you’d like to be part of this conversation.

**Comment by chosww** [comment]
@sepidehshahi any updates on the blurb and image?

**Comment by sepidehshahi** [comment]
No @chosww I'm still waiting for Colin to share that content
